# coding:utf-8

AGENT_ACTIVATE_REPORT_INTERVAL = 10
AGENT_NO_ACTIVATE_THRESHOLD = 60

AGENT_CHECK_OUT_OF_CONTROL_BROWSER_INTERVAL = 20
AGENT_CHECK_FREE_BROWSER_MISMATCH_INTERVAL = 10

API_SERVER_CHECK_BUSY_EVENT_TIME = 10


BROWSER_PER_AGENT = 3


SECRET_TOKEN = 'CHANGE ME'
